name: setup-pnpm
description: 'Setup dependencies with pnpm'

inputs:
  working-directory:
    required: false
    type: string
    default: '.'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        package_json_file: ${{ inputs.working-directory }}/package.json
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version-file: ${{ inputs.working-directory }}/.node-version
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml
    - shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
      working-directory: ${{ inputs.working-directory }}
