name: setup-pnpm
description: 'Setup dependencies with pnpm'

inputs:
  working-directory:
    required: false
    type: string
    default: '.'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        package_json_file: ${{ inputs.working-directory }}/package.json
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: ${{ inputs.working-directory }}/.node-version
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml
    - shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
      working-directory: ${{ inputs.working-directory }}
