name: setup-pnpm
description: 'Setup dependencies with pnpm'

inputs:
  working-directory:
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
      with:
        package_json_file: ${{ inputs.working-directory }}/package.json
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version-file: ${{ inputs.working-directory }}/.node-version
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml
    - shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
      working-directory: ${{ inputs.working-directory }}
