name: 'Setup dependencies with yarn'
inputs:
  node-version-file:
    required: true
  working-directory:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup node env 🏗
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: yarn

    - name: Install dependencies 👨🏻‍💻
      run: yarn
      shell: bash
      working-directory: ${{ inputs.working-directory }}
